## 应用服务端口
server:
  port: 80

## mysql configuration
spring:
  datasource:
    driver-class-name: @project.driver@
    url: @project.url@
    username: @project.username@
    password:
    max-active: 10
    max-idle: 5
    min-idle: 0

  h2:
    console:
      enabled: true #开启web console功能

## mybatis configuration
mybatis:
  mapper-locations: classpath:/mybatis/*.xml,classpath:/mybatis/**/*.xml
  type-aliases-package: com.lotus.example